### ISSUE TITLE
Any idea why this happens on fresh npm install v2x and v3x?

### ISSUE THREAD

**Issue by adjavaherian** [shinnn/exec-series#1]
```
> gifsicle@3.0.3 postinstall /home/me/hotpads-web/node_modules/gifsicle
> node lib/install.js

module.js:340
    throw err;
    ^

Error: Cannot find module 'async-each-series'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/me/node_modules/exec-series/index.js:10:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
```

async seems to be listed as a dependency and after second npm install, there are no more exceptions.

```
└─┬ gulp-imagemin@2.4.0
  └─┬ imagemin@4.0.0
    └─┬ imagemin-gifsicle@4.2.0
      └─┬ gifsicle@3.0.3
        └─┬ bin-build@2.2.0
          └─┬ exec-series@1.0.2
            └── async-each-series@1.1.0 
```

Thanks!

**Comment by dalgleish** [comment]
Happens with

``` bash
$ npm --version
2.14.12
```

**Comment by shinnn** [comment]
Thanks for the report but this is an [npm](https://github.com/npm/npm) issue.
